### ISSUE TITLE
Error in Build input file & Type() in ContentView.swift file

### ISSUE THREAD

**Issue by azeemohd786** [djmunish/CoronaStats-iOS#2]
I tried to run this project after clone and download but it failed to run showing following errors,

Error 1: Type '()' cannot conform to 'View'; only struct/enum/class types can conform to protocols in ContentView.swift file

Error2:- is in build error: Build input file cannot be found: '/Applications/iOS Projects/CoronaStats-iOS/CoronaWatch/Base.lproj/Interface.storyboard' (in target 'CoronaWatch' from project 'CoronaTracker')

Could you fix this..

**Comment by djmunish** [comment]
Fixed in the latest code, Please pull the latest code and try.

**Comment by azeemohd786** [comment]
@djmunish Thank you, I must say its fantastic UI, appreciate your effort!..

**Comment by djmunish** [comment]
Thanks, feel free to add more features to it and send Pull Request.
